site_name: torch_pointcloud
site_description: PyTorch Point Cloud models, scripts, pretrained weights and more.
strict: true
site_url: https://github.com/arthurdjn/pytorch-pointcloud

theme:
  name: "material"
  custom_dir: "docs/theme"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: purple
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: purple
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"

  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - navigation.prune
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.prune
    - navigation.footer
    - navigation.tracking
    - navigation.sections # navigation.expand or navigation.sections
    - search.suggest
    - toc.follow

repo_name: arthurdjn/torch_pointcloud
repo_url: https://github.com/arthurdjn/pytorch-pointcloud
edit_uri: edit/main/docs/

# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

extra_javascript:
  - js/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - "css/style.css"
  - https://unpkg.com/katex@0/dist/katex.min.css

nav:
  - Get Started:
      - Welcome to torch_pointcloud: index.md
  - API Reference:
      - Datasets: api/datasets.md
      - Utils: api/utils.md

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.extra
  - pymdownx.emoji:
  - pymdownx.tabbed:
      alternate_style: true
  # For math equations
  - pymdownx.arithmatex:
      generic: true

watch:
  - src/torch_pointcloud

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            show_root_heading: true
            # heading_level: 1
            members_order: source
            separate_signature: true
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_signature_annotations: true
            signature_crossrefs: true
            show_labels: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
  - mkdocs-jupyter:
      theme: dark
      include_source: True
  - mkdocs-simple-hooks:
      hooks:
        on_pre_build: "docs.plugins.main:on_pre_build"
  - exclude:
      glob:
        - theme/announce.html
        - plugins/*
        - __pycache__/*
