[project]
name = "torch-pointcloud"
version = "0.1.0"
description = "PyTorch Point Cloud models, scripts, pretrained weights and more"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "joblib>=1.4.2",
    "nbformat>=5.10.4",
    "numpy>=2.0.0",
    "open3d>=0.19.0",
    "pandas>=2.2.3",
    "plotly>=6.0.0",
    "plyfile>=1.1",
    "torch>=2.0.0",
    "tqdm>=4.67.1",
]

[tool.uv]
package = true
dev-dependencies = [
    "mypy>=1.14.1",
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
    "ruff>=0.9.1",
    "ipykernel>=6.29.5",
    "mkdocs-jupyter>=0.25.1",
    "mkdocs-simple-hooks>=0.1.5",
    "mkdocs-exclude>=1.0.2",
    "nbconvert>=7.16.5",
    "mkdocstrings>=0.27.0",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.5.50",
    "mkdocstrings-python>=1.13.0",
    "types-requests>=2.32.0.20241016",
]

[tool.ruff]
target-version = "py310"
line-length = 120

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"src/**/__init__.py" = ["F401"]

[tool.ruff.lint.isort]
known-first-party = ["torch_pointcloud"]

[tool.mypy]
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
no_implicit_optional = true
show_error_codes = true
ignore_missing_imports = true
explicit_package_bases = true
check_untyped_defs = true
implicit_reexport = true
