from ._registry import create_model, register_model
from .kpconv import KPConvNetClassification, KPConvNetSegmentation
from .point_transformer import PointTransformerClassification, PointTransformerSegmentation
from .point_transformer_v2 import PointTransformerV2Classification, PointTransformerV2Segmentation
from .point_transformer_v3 import PointTransformerV3Classification, PointTransformerV3Segmentation
from .pointnet import PointNetClassification, PointNetEncoder, PointNetSegmentation
from .pointnet2 import PointNet2Classification, PointNet2Segmentation
from .pvcnn import PVCNNClassification, PVCNNSegmentation
from .pvcnn2 import PVCNN2Classification, PVCNN2Segmentation
from .randlanet import RandLANetClassification, RandLANetSegmentation
from .spvcnn import SPVCNNClassification, SPVCNNSegmentation
