"""Render the committed example notebooks into Markdown pages for the docs site.

`zensical` has no native notebook rendering, so this converts each
`docs/examples/*.ipynb` into a `docs/examples/<name>.md` page with `nbconvert`
(no execution), inserting Open-in-Colab and download links just below the title.
The notebooks are the source of truth; the generated `.md` files are build
artifacts (git-ignored) and are regenerated by `make docs` / `make serve`.

Usage:
    uv run --no-sync python docs/scripts/build_examples.py
"""

import argparse
from pathlib import Path

import nbformat
from nbconvert import MarkdownExporter

REPO = "arthurdjn/pytorch-pointcloud"
BRANCH = "main"
DOCS_DIR = Path(__file__).resolve().parents[1]
EXAMPLES_DIR = DOCS_DIR / "examples"


def badges(name: str) -> str:
    rel = f"docs/examples/{name}.ipynb"
    colab = f"https://colab.research.google.com/github/{REPO}/blob/{BRANCH}/{rel}"
    download = f"https://github.com/{REPO}/blob/{BRANCH}/{rel}"
    return f":colab: [Open in Colab]({colab}) · :github: [Download notebook]({download})"


def insert_badges(markdown: str, name: str) -> str:
    """Place the badge line directly under the page's first `#` heading."""
    line = badges(name)
    out: list[str] = []
    inserted = False
    for text in markdown.splitlines():
        out.append(text)
        if not inserted and text.startswith("# "):
            out += ["", line]
            inserted = True
    if not inserted:
        out = [line, ""] + out
    return "\n".join(out)


def render(path: Path, exporter: MarkdownExporter) -> Path:
    nb = nbformat.read(path, as_version=4)
    body, _ = exporter.from_notebook_node(nb)
    out = path.with_suffix(".md")
    out.write_text(insert_badges(body.strip(), path.stem) + "\n")
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description="Render example notebooks to Markdown.")
    parser.add_argument("--dir", default=EXAMPLES_DIR, type=Path)
    args = parser.parse_args()

    exporter = MarkdownExporter()
    notebooks = sorted(args.dir.glob("*.ipynb"))
    for path in notebooks:
        out = render(path, exporter)
        print(f"Rendered: {out.relative_to(DOCS_DIR.parent)}")
    print(f"Rendered {len(notebooks)} notebooks.")


if __name__ == "__main__":
    main()
