"""Render the committed notebooks into Markdown pages for the docs site.

`zensical` has no native notebook rendering, so this converts every notebook of a
docs section (`docs/<section>/<name>.ipynb`) into a sibling `<name>.md` page with
`nbconvert` (no execution, stored outputs stripped), inserting Open-in-Colab and
download links just below the title. The notebooks are the source of truth; the
generated `.md` files are build artifacts (git-ignored) and are regenerated by
`make docs` / `make serve`.

Usage:
    uv run --no-sync python docs/scripts/build_notebooks.py
"""

import argparse
from pathlib import Path

import nbformat
from nbconvert import MarkdownExporter

REPO = "arthurdjn/pytorch-pointcloud"
BRANCH = "main"
DOCS_DIR = Path(__file__).resolve().parents[1]
REPO_DIR = DOCS_DIR.parent
# Model pages end with their task's checkpoint table, rendered by the `model_table` macro from `docs/data/models.csv`.
MODEL_TABLES = {
    "models/classification.ipynb": "classification",
    "models/segmentation.ipynb": "semantic-segmentation",
    "models/part-segmentation.ipynb": "part-segmentation",
    "models/detection.ipynb": "detection",
    "models/features.ipynb": "pretraining",
}


def badges(path: Path) -> str:
    rel = path.relative_to(REPO_DIR).as_posix()
    colab = f"https://colab.research.google.com/github/{REPO}/blob/{BRANCH}/{rel}"
    download = f"https://github.com/{REPO}/blob/{BRANCH}/{rel}"
    return f":colab: [Open in Colab]({colab}) · :github: [Download notebook]({download})"


def insert_badges(markdown: str, path: Path) -> str:
    """Place the badge line directly under the page's first `#` heading."""
    line = badges(path)
    out: list[str] = []
    inserted = False
    for text in markdown.splitlines():
        out.append(text)
        if not inserted and text.startswith("# "):
            out += ["", line]
            inserted = True
    if not inserted:
        out = [line, ""] + out
    return "\n".join(out)


def render(path: Path, exporter: MarkdownExporter) -> Path:
    nb = nbformat.read(path, as_version=4)
    body, _ = exporter.from_notebook_node(nb)
    markdown = insert_badges(body.strip(), path)
    task = MODEL_TABLES.get(path.relative_to(DOCS_DIR).as_posix())
    if task:
        markdown += f'\n\n## Checkpoints\n\n{{{{ model_table("{task}") }}}}'
    out = path.with_suffix(".md")
    out.write_text(markdown + "\n")
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description="Render notebooks to Markdown.")
    parser.add_argument("--dir", default=DOCS_DIR, type=Path)
    args = parser.parse_args()

    exporter = MarkdownExporter(exclude_output=True)
    notebooks = sorted(args.dir.glob("*/*.ipynb"))
    for path in notebooks:
        out = render(path, exporter)
        print(f"Rendered: {out.relative_to(REPO_DIR)}")
    print(f"Rendered {len(notebooks)} notebooks.")


if __name__ == "__main__":
    main()
