name: Code Quality

on: push

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.10"

      - name: Install all extras
        # NOTE: Do not install flash-attn here, as it requires CUDA
        run: uv sync --extra spconv ocnn pyg-lib

      - name: Check types
        if: ${{ always() }}
        run: uv run mypy src tests examples

      - name: Check linting
        if: ${{ always() }}
        run: uv run ruff check src tests examples

      - name: Check imports
        if: ${{ always() }}
        run: uv run ruff check src tests examples --select I

      - name: Check formatting
        if: ${{ always() }}
        run: uv run ruff format src tests examples --check
