name: Code Quality

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.10"

      - name: Install package (torch==2.6.0)
        run: |
          uv add torch==2.6.0
          uv sync --frozen

      - name: Install torch
        run: uv pip install --no-config torch==2.6.0 --index-url https://download.pytorch.org/whl/cpu

      - name: Install torchvision
        run: uv pip install --no-config torchvision==0.21.0 --index-url https://download.pytorch.org/whl/cpu

      - name: Install ocnn
        run: uv pip install --no-deps 'ocnn==2.2.8'

      - name: Install torch-scatter + torch-cluster
        run: uv pip install torch-scatter torch-cluster -f https://data.pyg.org/whl/torch-2.6.0+cpu.html

      - name: Install spconv
        run: uv pip install spconv

      - name: Check types
        if: ${{ always() }}
        run: uv run mypy src tests examples

      - name: Check linting
        if: ${{ always() }}
        run: uv run ruff check src tests examples

      - name: Check imports
        if: ${{ always() }}
        run: uv run ruff check src tests examples --select I

      - name: Check formatting
        if: ${{ always() }}
        run: uv run ruff format src tests examples --check
