name: Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Add ocnn dependency for python ${{ matrix.python-version }}
        # NOTE: ocnn depends on torchvision, which is not fully compatible with python 3.13 yet
        if: matrix.python-version != '3.13'
        run: echo "UV_SYNC_ARGS=${{ env.UV_SYNC_ARGS }} --extra ocnn" >> $GITHUB_ENV

      - name: Install torch-geometric dependencies
        # NOTE: `pyg-lib` has no wheels for python 3.13 yet
        if: matrix.python-version != '3.13'
        run: echo "UV_SYNC_ARGS=${{ env.UV_SYNC_ARGS }} --extra pyg-lib" >> $GITHUB_ENV

      - name: Install spconv dependency
        run: echo "UV_SYNC_ARGS=${{ env.UV_SYNC_ARGS }} --extra spconv" >> $GITHUB_ENV

      - name: Install flash-attn dependency
        if: runner.os == 'Linux' && contains(runner.name, 'gpu')
        run: echo "UV_SYNC_ARGS=${{ env.UV_SYNC_ARGS }} --extra flash-attn" >> $GITHUB_ENV

      - name: Install all dependencies (torch==2.6.0)
        run: |
          echo "UV_SYNC_ARGS=${{ env.UV_SYNC_ARGS }}"
          uv add torch==2.6.0
          uv sync ${{ env.UV_SYNC_ARGS }} --frozen

      - name: Test with python ${{ matrix.python-version }}
        run: uv run --frozen pytest
